SGLang.lang = $.extend(SGLang.lang, {
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolNameElevation: "Elevation Layers Comparison",
    ToolNameMesh: "3D Mesh Layers Comparison",
    ToolNameBoth: "Elevation Comparison",
    resultHeader: "Elevation Comparison Results",
    help: "Help",
    selectLayer1: "Layer #1",
    selectLayer2: "Layer #2",
    compare: "Compare",
    terrain: "Base Map",
    select: "Select",
    tolerance: "Min Difference",
    quality: "Quality",
    low: "Low",
    medium: "Medium",
    high: "High",
    refresh: "Refresh & Detect",
    drawObjects: "Results Layer",
    startCalculate: "Start<br\>Calculation",
    drawArea: "Draw<br\>Area",
    fromClipboard: "From<br>Clipboard",
    hideOtherLayers: "** All other layers in the area of the elevation comparison should be hidden so that they don't interfere with the tool's results.",
    noPolygon: "No polygon objects were detected on the clipboard",
    sameLayers: "Please select different layers from 'Layers #1' and 'Layers #2' lists",
    polygonNotIntersect: "The area polygon geometry does not intersect with the selected layers",
    meters: "meters",
    sqm: "square meters",
    cubicm: "cubic meter",
    feet: "feet",
    sqft: "square foot",
    cubicf: "cubic foot",
    elevationComparison: "ElevationComparison",
    volume: "Volume",
    volumeType: "VolumeType",
    SampleArea: "SampleArea",
    sampleAreaTitle: "Sample Area",
    volumeChange: "Volume Difference",
    volumeDiff: "VolumeDiff",
    elevationDiff: "ElevDiff",
    elevationDifference: "Elevation Difference",
    totalSamples: "Total number of samples: ",
    sampledPoints :"Sampled points",
    totalIdentified: "Total: ",
    sampledPointsAbove: "Sampled points above min difference",
    totalPositive: "layer #1 higher than layer #2: ",
    totalNegative: "layer #2 higher than layer #1: ",
    maxElevation: "Max elevation difference",
    maxPositive: "Layer #1 is higher than layer #2: ",
    maxNegative: "Layer #2 is higher than layer #1: ",
    volumeTitle: "Volume Analysis Results ",
    volumeAdded: "Volume Fill: ",
    volumeRemoved: "Volume Cut: ",
    volumeTotalNet: "Total net volume: ",
    cut: "(cut)",
    fill: "(fill)",
    volumeEqual: "No Change",
    PrepareClaculation: "Generating elevation buffers...",
    calculatingVolume: "Calculating volume of object ",
    drawPolygon: "To calculate the volume difference between an elevation layer and the base terrain, draw a polygon marking your area of interest ",
    selectLayer: "-- Select a Layer --",
    color: "Color",
    noElevation: "Could not find elevation layer overlap with the selected polygon",
    Text_Swipe3DMLBtn: "Swipe Layers",
    Text_Swipe3DML: "Swipe 3D Mesh Layers",
    Text_AlertCaption: "TerraExplorer",
    TextAbort: " (Esc to abort)",
    
    Text999: ""
});

